package com.tallerfinal.springfinal;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;

class PostgresEmbebidoTest extends PruebaIntegracion {

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@Test
	void lasPruebasUsanElPostgresqlEmbebido() {
		String version = jdbcTemplate.queryForObject("select version()", String.class);
		String url = jdbcTemplate.execute((ConnectionCallback<String>) conexion -> conexion.getMetaData().getURL());

		assertThat(version).startsWith("PostgreSQL");
		assertThat(url).startsWith("jdbc:postgresql://localhost:");
	}

	@Test
	void vaciarTablasBorraLasFilasYReiniciaLosIdentificadores() {
		jdbcTemplate.execute("create table prueba_vaciado (id bigint generated by default as identity primary key, nombre text)");
		try {
			jdbcTemplate.update("insert into prueba_vaciado (nombre) values ('a'), ('b')");

			vaciarTablas();

			assertThat(jdbcTemplate.queryForObject("select count(*) from prueba_vaciado", Integer.class)).isZero();
			jdbcTemplate.update("insert into prueba_vaciado (nombre) values ('c')");
			assertThat(jdbcTemplate.queryForObject("select id from prueba_vaciado", Long.class)).isEqualTo(1L);
		}
		finally {
			jdbcTemplate.execute("drop table prueba_vaciado");
		}
	}

}
