spring.application.name=tallerautos

spring.datasource.url=jdbc:postgresql://localhost:5432/tallerautos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

tasa.api.url=https://open.er-api.com/v6/latest/USD
tasa.api.timeout-ms=3000
tasa.cache-minutes=30
tasa.valor-por-defecto=3200

server.port=8080

spring.web.resources.add-mappings=true

logging.level.com.tallerautos=INFO
